name: Wake up Render instance

on:
  schedule:
    # 07:58 Paris = 05:58 UTC
    - cron: "58 5 * * *"

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Call wake up endpoint
        run: |
          curl -X POST https://la-grandeur-des-choses.onrender.com/ping
